site_name: AcessibilidadeJá
site_url: https://unbarqdsw2026-1-turma02.github.io/2026.01-T02_G4_AcessibilidadeJa_Entrega_03
repo_url: https://github.com/UnBArqDsw2026-1-Turma02/2026.01-T02_G4_AcessibilidadeJa_Entrega_03
repo_name: UnBArqDsw2026-1-Turma02/2026.01-T02_G4_AcessibilidadeJa_Entrega_03

use_directory_urls: false

nav:
  - Início - AcessibilidadeJá: "index.md"
  - GoFs Criacionais:
      - GoFs Criacionais: PadroesDeProjeto/3.1.GoFsCriacionais.md
  - GoFs Estruturais:
      - GoFs Estruturais: PadroesDeProjeto/3.2.GoFsEstruturais.md
  - GoFs Comportamentais:
      - GoFs Comportamentais: PadroesDeProjeto/3.3.GoFsComportamentais.md
  - Participações:
      - Participações: PadroesDeProjeto/3.4.ParticipacoesPadroes.md
  - Iniciativas Extras:
      - Iniciativas Extras: PadroesDeProjeto/3.5.IniciativasExtras.md

theme:
  name: material
  locale: pt_BR
  logo: images/acessibilidade.svg
  favicon: images/acessibilidade.png

  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.top
    - navigation.expand

  palette:
    - scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Modo escuro
    - scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Modo claro
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/progresso-checkbox.js
  - js/back-to-top.js
  - https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js
  - js/jspdf.umd.min.js
  - js/relatorio-checklist.js
